### ISSUE TITLE
Sample buffer renderer & backgrounding

### ISSUE THREAD

**Issue by ceaglest** [perchco/perchrtc#1]
The sample buffer renderer doesn't like being backgrounded during an active connection. AVSampleBufferDisplayLayer is very fickle about the application lifecycle: It immediately goes to the "failed" status as soon as your app enters the background, even if no frames are being actively enqueued to it.

**Comment by FernandoWei** [comment]
Hi ceaglest, have you ever fix it? I also suffer from it.
