### ISSUE TITLE
Crash m45

### ISSUE THREAD

**Issue by ghost** [perchco/perchrtc#14]
Hi, I have crash in VideoCapturerKit::~VideoCapturerKit() webrtc - m45 https://monosnap.com/file/ljQqjUSAZnQwHg8JEuBBMZwwuLqrny

any ideas?

**Comment by ceaglest** [comment]
@Pro100Andrey thanks for the feedback, I am also seeing a crash when deallocating the capturer in Chrome 45. I'm still working on this lifecycle issue and a couple of performance related issues before closing out the feature branch.

**Comment by ghost** [comment]
@ceaglest crashed only webrtc release libs

**Comment by ghost** [comment]
@ceaglest fixed in latest webrtc revision

**Comment by ghost** [comment]
and add in your sample 

GCC_PREPROCESSOR_DEFINITIONS = 

V8_DEPRECATION_WARNINGS EXPAT_RELATIVE_PATH FEATURE_ENABLE_VOICEMAIL GTEST_RELATIVE_PATH JSONCPP_RELATIVE_PATH LOGGING=1 SRTP_RELATIVE_PATH FEATURE_ENABLE_SSL FEATURE_ENABLE_PSTN HAVE_SCTP HAVE_SRTP HAVE_WEBRTC_VIDEO HAVE_WEBRTC_VOICE DISABLE_NACL CHROMIUM_BUILD CR_CLANG_REVISION=239765-1 USE_LIBJPEG_TURBO=1 ENABLE_CONFIGURATION_POLICY SYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE DONT_EMBED_BUILD_METADATA CLD_VERSION=2 DISABLE_FTP_SUPPORT=1 V8_USE_EXTERNAL_STARTUP_DATA IOS WEBRTC_MAC WEBRTC_IOS CARBON_DEPRECATED=YES HASH_NAMESPACE=__gnu_cxx WEBRTC_POSIX DISABLE_DYNAMIC_CAST _REENTRANT USE_LIBPCI=1 USE_OPENSSL=1 NDEBUG NVALGRIND DYNAMIC_ANNOTATIONS_ENABLED=0 NS_BLOCK_ASSERTIONS=1

this worked for me )))

**Comment by ceaglest** [comment]
Thanks @Pro100Andrey, the additional preprocessor defines fixed the crash here as well. This has been updated on the feature branch.
