### ISSUE TITLE
iOS9

### ISSUE THREAD

**Issue by ckroll2** [perchco/perchrtc#16]
Hi, 

Have you been successful running this demo on iOS9? If I disable bitcode I can get it to build, but the audio is really poor and there are some timescale errors in the debug output. Is there an updated nighthawk podspec file?

Thanks

**Comment by ceaglest** [comment]
@ckroll2 I haven't tested this on iOS 9 yet unfortunately. I can have a look this weekend to see if I have the same issues.

For reference, are you using the Chrome 45 branch? That will probably fare much better than the older Chrome 42 based stuff on master.

**Comment by ckroll2** [comment]
I'm using master. I'll give the branch a shot - it doesn't seem to be iOS 9
but rather the 6S device. There is a significant amount of audio
degradation.

On Thu, Oct 1, 2015 at 2:29 PM, Christopher Eagleston <
notifications@github.com> wrote:

> @ckroll2 https://github.com/ckroll2 I haven't tested this on iOS 9 yet
> unfortunately. Can have a look this weekend to see if I have the same
> issues.
> 
> For reference, are you using the Chrome 45 branch? That will probably fare
> much better than the older Chrome 42 based stuff on master.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/perchco/perchrtc/issues/16#issuecomment-144809859.

## 

-Colin Kroll

**Comment by ckroll2** [comment]
@ceaglest would it be possible to contact you via e-mail? I'm colinkroll a t gmail

**Comment by ckroll2** [comment]
I ran in to the same issue with the branch

**Comment by ceaglest** [comment]
@ckroll2 Chrome 47 includes a refactored audio device implementation for iOS that offers better support for the iPhone 6S. Will see if I can get PerchRTC updated to fix this issue.

**Comment by ceaglest** [comment]
@ckroll2 I just merged a fix for the project file into master. At the moment bit code is disabled, but this will  be possible in future builds. Will open a new ticket to track audio issues and bit code build settings.

**Comment by whydna** [comment]
@ceaglest  can you link to the merge with this fix?

Thanks!
