### ISSUE TITLE
.mm file invisible to other files. 

### ISSUE THREAD

**Issue by dreamfm** [perchco/perchrtc#17]
Hi, i don't know if this is too much to ask of you. 

But i have been experimenting with your project for a while and I have decided to write something on top of what you guys have developed just for learning. 

For your PHVideoCaptureKit, which is written in c++ (.mm format), when i extract this particular folder to my own app, somehow, all my other folders will not be able to see it. I can't use any protocols or classes that are defined in PHVideoCaptureKit. Whenever i attempt to, error such as "No defined type" pops out.

However, it runs perfectly in the sample app you guys developed. I am just wondering how do you guys do that? 

I have been asking around, all the suggestions/answers were writing another wrapper for the class and something along the line, but i am really curious how you guys manage to do it. 

Thanks

Regards

**Comment by ceaglest** [comment]
Hi @dreamfm,

I've been meaning to package up this project as a drop in SDK, as I've had quite a few developers asking in public and private how to get it into their own projects. It's likely the issue you're running into is just the special compiler flags needed to build PHVideoCaptureKit classes.

See if this issue provides a temporary fix: https://github.com/perchco/perchrtc/issues/6

Cheers,
Chris

**Comment by dreamfm** [comment]
@ceaglest

Thanks for the prompt reply. But, I have already added the compiler before asking. To be honest,i have tried quite a few ways to achieve what you did, but to no veil. 

You can try to extract the file out and compile on an empty application, somehow the PHVideoCaptureKit just stays invisible. 

I was just really curious and amazed at how you guys make that work without writing extra wrappers .

But once again, admit your dedication for the project and appreciate the prompt reply. Maybe i will just write a wrapper to see if it works. 

Regards
