### ISSUE TITLE
Web socket does not connect on iOS 9?

### ISSUE THREAD

**Issue by whydna** [perchco/perchrtc#25]
Seems there is some issue with new versions of the Pods (SRWebSocket?)

Reproduce:
- Clone project
- rm Podfile.lock
- Change Podfile iOS target from 7.0 -> 9.0
- Build and Run.

It's not able to connect with the Xirsys socket. It immediately disconnects.

**Comment by ceaglest** [comment]
@whydna The Websocket server URL is hardcoded, but it shouldn't be. It's entirely possible XirSys has changed it, as I was having no problems connecting the last time I tested on 9.1.

See: https://github.com/perchco/perchrtc/issues/24

**Comment by ceaglest** [comment]
@whydna Give this a try. Thanks!

https://github.com/perchco/perchrtc/pull/26
