### ISSUE TITLE
Connecting to web application

### ISSUE THREAD

**Issue by dreamfm** [perchco/perchrtc#30]
Hi, i have been playing around the PerchIOS app and it works fine on the mobile platform. 

Now i have built a rather simple Peerjs web application and i wish to use the IOS app to connect to the web application. However, there is an error on connecting. 

On the web application, i need to create a new user, for example, MrX, and joins the room. When i  press connect on the mobile app, the connecting displaying message is (Connecting to Peers) rather than "connecting to web application user name"... Also, the mobile user's name becomes visible on the "call-peer" list, for example, MrY, on the web application, but when i press the connect button on the web application, it says connection failure. 

What i am wondering is that, is there something wrong with the default peer choice in the Mobile application in this case? Because on the mobile itself, we don't have the option of selecting which peer to connect to, but rather, we connect to the default peer we see in the room? 

How do i fix that? 

Btw, the Peerjs Demo is from the XirSys SDK 

https://github.com/xirdev/xsdk 

Thanks very much 

Regards

**Comment by dreamfm** [comment]
Alright, i think the problem doesn't lie in the peer selection part, but rather the mobile to web browser connectivity part.

**Comment by ceaglest** [comment]
@dreamfm I haven't tried the Peerjs demo from XirSys but I don't think the application level signaling used is the same as PerchRTC. Both clients need to send the same types of messages, with an agreed upon payload.

**Comment by dreamfm** [comment]
@ceaglest 

Hi, Thanks for the prompt reply.. Can you point me to a direction on how i may solve this? Or is it going to be too complicated? 

Thanks

**Comment by ceaglest** [comment]
@dreamfm In this example the message keys are defined in: https://github.com/perchco/perchrtc/blob/master/PerchRTC/XirSys/XSMessage.h

Despite the fact that both sample apps use the XirSys signaling server the clients still need to speak in terms of the same message types.
